version: '2'

networks:
  my_network:
    driver: bridge

services:
  app:
    image: adoptopenjdk:11-jdk-hotspot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521/XE
      - SPRING_DATASOURCE_USERNAME=kjvargas
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_DATABASE_PLATFORM=oracle.jdbc.OracleDriver
    ports:
      - "8080:8080"
    networks:
      - my_network

  db:
    image: 'container-registry.oracle.com/database/express'
    container_name: db
    environment:
      - ORACLE_SID=XE
      - ORACLE_PWD=12345
    ports:
      - "5679:1521"
    networks:
      - my_network

volumes:
  oracledb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/oracle/oradata
