FROM container-registry.oracle.com/database/express:18.4.0-xe

ENV DBCA_NON_INTERACTIVE=true
ENV ORACLE_PWD=12345

COPY user.sql /tmp/user.sql

RUN echo -e 'exit' | sqlplus sys/12345@//localhost:1521/xe as sysdba @/tmp/user.sql
#ENTRYPOINT ["sqlplus", "sys/12345@//localhost:1521/xe", "as", "sysdba"]
#ENTRYPOINT ["@/tmp/user.sql"]
EXPOSE 1521
