version: '3'

services:
  db:
    image: 'gvenzl/oracle-xe:latest-faststart'
    container_name: db
    environment:
      - ORACLE_PASSWORD=12345
    ports:
      - 1521:1521

  app:
    image: 'adm-usuario:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521/XE
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8080:8080