version: '3'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:18.4.0-xe
    environment:
      - ORACLE_PWD=12345
    ports:
      - "1521:1521"

  spring-app:
    build:
      dockerfile: Dockerfile-spring
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
